
package asg2client.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "asg2service", targetNamespace = "http://asg2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Asg2Service {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "List")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "List", targetNamespace = "http://asg2/", className = "asg2client.service.List")
    @ResponseWrapper(localName = "ListResponse", targetNamespace = "http://asg2/", className = "asg2client.service.ListResponse")
    @Action(input = "http://asg2/asg2service/ListRequest", output = "http://asg2/asg2service/ListResponse")
    public List<String> List(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "edit", targetNamespace = "http://asg2/", className = "asg2client.service.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://asg2/", className = "asg2client.service.EditResponse")
    @Action(input = "http://asg2/asg2service/editRequest", output = "http://asg2/asg2service/editResponse")
    public int edit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorldFrom", targetNamespace = "http://asg2/", className = "asg2client.service.SayHelloWorldFrom")
    @ResponseWrapper(localName = "sayHelloWorldFromResponse", targetNamespace = "http://asg2/", className = "asg2client.service.SayHelloWorldFromResponse")
    @Action(input = "http://asg2/asg2service/sayHelloWorldFromRequest", output = "http://asg2/asg2service/sayHelloWorldFromResponse")
    public String sayHelloWorldFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "book", targetNamespace = "http://asg2/", className = "asg2client.service.Book")
    @ResponseWrapper(localName = "bookResponse", targetNamespace = "http://asg2/", className = "asg2client.service.BookResponse")
    @Action(input = "http://asg2/asg2service/bookRequest", output = "http://asg2/asg2service/bookResponse")
    public List<String> book(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "List1")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "List1", targetNamespace = "http://asg2/", className = "asg2client.service.List1")
    @ResponseWrapper(localName = "List1Response", targetNamespace = "http://asg2/", className = "asg2client.service.List1Response")
    @Action(input = "http://asg2/asg2service/List1Request", output = "http://asg2/asg2service/List1Response")
    public String List1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerTrips", targetNamespace = "http://asg2/", className = "asg2client.service.GetCustomerTrips")
    @ResponseWrapper(localName = "getCustomerTripsResponse", targetNamespace = "http://asg2/", className = "asg2client.service.GetCustomerTripsResponse")
    @Action(input = "http://asg2/asg2service/getCustomerTripsRequest", output = "http://asg2/asg2service/getCustomerTripsResponse")
    public List<String> getCustomerTrips(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
