
package asg2client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "asg2serviceService", targetNamespace = "http://asg2/", wsdlLocation = "http://localhost:8080/asg2_war_exploded/services/asg2_service?wsdl")
public class Asg2ServiceService
    extends Service
{

    private final static URL ASG2SERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ASG2SERVICESERVICE_EXCEPTION;
    private final static QName ASG2SERVICESERVICE_QNAME = new QName("http://asg2/", "asg2serviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/asg2_war_exploded/services/asg2_service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASG2SERVICESERVICE_WSDL_LOCATION = url;
        ASG2SERVICESERVICE_EXCEPTION = e;
    }

    public Asg2ServiceService() {
        super(__getWsdlLocation(), ASG2SERVICESERVICE_QNAME);
    }

    public Asg2ServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASG2SERVICESERVICE_QNAME, features);
    }

    public Asg2ServiceService(URL wsdlLocation) {
        super(wsdlLocation, ASG2SERVICESERVICE_QNAME);
    }

    public Asg2ServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASG2SERVICESERVICE_QNAME, features);
    }

    public Asg2ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Asg2ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Asg2Service
     */
    @WebEndpoint(name = "asg2servicePort")
    public Asg2Service getAsg2ServicePort() {
        return super.getPort(new QName("http://asg2/", "asg2servicePort"), Asg2Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Asg2Service
     */
    @WebEndpoint(name = "asg2servicePort")
    public Asg2Service getAsg2ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://asg2/", "asg2servicePort"), Asg2Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASG2SERVICESERVICE_EXCEPTION!= null) {
            throw ASG2SERVICESERVICE_EXCEPTION;
        }
        return ASG2SERVICESERVICE_WSDL_LOCATION;
    }

}
